### ISSUE TITLE
Exit Code: 255 Mac wont even start up game

### ISSUE THREAD

**Issue by coll087** [FTBTeam/FTB-App-Feedback#137]
### What Operating System

MacOS (Latest)

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

--- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2/11/22 4:24 PM
Description: Initializing game

java.lang.IllegalStateException: GLFW error before init: [0x10008]Cocoa: Failed to find service port for display
	at com.mojang.blaze3d.platform.GLX.func_229879_lam_(SourceFile:64) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_211162_a(MainWindow.java:131) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:MainWindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:1060) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:416) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:minetogether.mixins.json:MixinMinecraftTitle,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.5-forge-36.2.22.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX.func_229879_lam_(SourceFile:64) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_211162_a(MainWindow.java:131) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:MainWindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:63) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:1060) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:416) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:minetogether.mixins.json:MixinMinecraftTitle,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.5-forge-36.2.22.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 686861936 bytes (655 MB) / 965214208 bytes (920 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx4096M
	Launched Version: 1.16.5-forge-36.2.22
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>

### Debug Code

??

### Describe the bug

wont start launcher

### Steps to reproduce

i have no idea as i cant code so im not sure

### Expected behaviour

launch ftb app on Minecraft

### Additional information

I dont know how to code or anything... this version of app wont launch on my mac but did only once when i first downloaded ftb. i need help as i really want to play this mod but it wont launch at all. the new beta version doesnt even open up launcher only gives exit code 1.

**Comment by MichaelHillcox** [comment]
This version of the app has already been superseded. Please wait for the update and let us know if this happens after that.

**Comment by coll087** [comment]
what does superseded mean? And also the newest version of the app gives me a crash code of exit code 1. ocean block doesnt work either and gives the same crash code of 255.

**Comment by MichaelHillcox** [comment]
Superseded means that there is something newer. What is the newest version of the app? The one you've stated is out of date

**Comment by coll087** [comment]
Is it the actual FTB app that is downloaded onto the mac because if so ive only just downloaded it from the website.

**Comment by coll087** [comment]
202112101445-bdf8bdbaca-release is the app version

**Comment by MichaelHillcox** [comment]
Again, there is a newer version coming out. We're at a 10% roll out, it'll be updated on MacOs and Linux in the coming hours

**Comment by coll087** [comment]
Thank you thats perfect hopefully it will be sorted out then. will i have to redownload the whole app and will it be on the ftb app website?

**Comment by MichaelHillcox** [comment]
It will be
