### ISSUE TITLE
"GPU process isn't usable" Error

### ISSUE THREAD

**Issue by benevolentmadman** [FTBTeam/FTB-App-Feedback#75]
### What Operating System

Linux (Ubuntu 20.04)

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Log Files

```
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: java.nio.file.NoSuchFileException: Games/FTBA/launcher-202110071354-4bdfd15050-release-all.jar
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1239)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at net.creeperhost.minetogether.lib.util.SignatureUtil.getSignature(SignatureUtil.java:28)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at net.creeperhost.creeperlauncher.Constants.<clinit>(Constants.java:72)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:78)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
[09:13:37] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at install4j.net.creeperhost.creeperlauncher.CreeperLauncher.main(Unknown Source)
[09:13:37] [main/INFO] [STDOUT]: [net.creeperhost.creeperlauncher.CreeperLauncher:main:78]: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[09:13:37] [main/INFO] [Instances]: Reloading instances..
[09:13:37] [main/INFO] [Instances]: Skipping Cloud instance reload.
[09:13:37] [main/INFO] [Modpack Installer Task]: Getting pack from api.
[09:13:37] [ForkJoinPool.commonPool-worker-5/INFO] [Modpack Installer Task]: Getting pack from api.
[09:13:37] [main/INFO] [Instances]: Loaded 3 out of 3 instances in 236ms(236762443ns).
[09:13:37] [main/INFO] [Instances]: Finished instance reload in 240ms(240797658ns)
[09:13:37] [main/INFO] [FTB Subprocess]: Electron integration mode
[09:13:37] [main/INFO] [FTB Subprocess]: No PID args specified
[09:13:37] [main/INFO] [FTB Subprocess]: Starting Electron: /Games/FTBA/bin/ftb-app --ws 19973:9fc73432-fe62-4855-adb4-2cc34a19db14 --pid 3031
[09:13:37] [WebSocketSelector-35/INFO] [Websockets API]: Server started successfully - 202110071354-4bdfd15050-release
[09:13:37] [main/INFO] [Instances]: Reloading instances..
[09:13:37] [main/INFO] [Instances]: Skipping Cloud instance reload.
[09:13:37] [main/INFO] [Modpack Installer Task]: Getting pack from api.
[09:13:37] [ForkJoinPool.commonPool-worker-9/INFO] [Modpack Installer Task]: Getting pack from api.
[09:13:37] [main/INFO] [Instances]: Loaded 3 out of 3 instances in 8ms(8852562ns).
[09:13:37] [main/INFO] [Instances]: Finished instance reload in 9ms(9482153ns)
[09:13:38] [ForkJoinPool.commonPool-worker-3/INFO] [FTB Subprocess]: 09:13:38.253 › We have a --ws
[09:13:38] [ForkJoinPool.commonPool-worker-3/INFO] [FTB Subprocess]: 09:13:38.258 › Got the lock
[09:13:38] [ForkJoinPool.commonPool-worker-5/ERROR] [FTB Subprocess]: 09:13:38.456 › (node:3097) ExtensionLoadWarning: Warnings loading extension at /home/alex/.config/ftb-app/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
[09:13:38] [ForkJoinPool.commonPool-worker-5/ERROR] [FTB Subprocess]:   Unrecognized manifest key 'browser_action'.
[09:13:38] [ForkJoinPool.commonPool-worker-5/ERROR] [FTB Subprocess]:   Unrecognized manifest key 'update_url'.
[09:13:38] [ForkJoinPool.commonPool-worker-5/ERROR] [FTB Subprocess]:   Permission 'contextMenus' is unknown or URL pattern is malformed.
[09:13:38] [ForkJoinPool.commonPool-worker-5/ERROR] [FTB Subprocess]:   Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
[09:13:38] [ForkJoinPool.commonPool-worker-5/ERROR] [FTB Subprocess]: 
[09:13:38] [ForkJoinPool.commonPool-worker-5/ERROR] [FTB Subprocess]: (Use `ftb-app --trace-warnings ...` to show where the warning was created)
[09:13:38] [WebSocketWorker-27/INFO] [Websockets API]: Front end connected: /127.0.0.1:35420
[09:13:44] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Checking for Launch Mod for instance 29367987-6643-4c57-b872-726b43408d4b}(FTB OceanBlock)..
[09:13:45] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Didn't find Launch Mod for instance 29367987-6643-4c57-b872-726b43408d4b(FTB OceanBlock) in 1313ms(1313049329ns).
[09:13:45] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Starting launcher at /home/alex/.ftba/bin
[09:13:45] [ForkJoinPool-1-worker-3/ERROR] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Unable to initialize MineTogether Connect!
[09:13:45] [ForkJoinPool.commonPool-worker-7/INFO] [Minecraft Launcher 0]: https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.689178:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 1 time(s)
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.692508:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 2 time(s)
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.693864:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 3 time(s)
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.695303:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 4 time(s)
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.696824:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 5 time(s)
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.698300:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 6 time(s)
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.700116:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 7 time(s)
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.740439:INFO:main_context.cpp(136)] CEF initialized successfully.
[09:13:52] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091352.740552:INFO:main_context.cpp(138)] CEF version: 86.0.23+ga2c2edf+chromium-86.0.4240.193
[09:13:53] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091353.222557:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 8 time(s)
[09:13:53] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091353.224495:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 9 time(s)
[09:13:53] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091353.224533:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
[09:13:53] [ForkJoinPool.commonPool-worker-7/INFO] [Minecraft Launcher 0]: https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
[09:13:58] [ForkJoinPool.commonPool-worker-7/INFO] [Minecraft Launcher 0]: OK
[09:13:58] [ForkJoinPool.commonPool-worker-7/INFO] [Minecraft Launcher 0]: https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.475580:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 1 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.477111:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 2 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.478376:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 3 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.479573:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 4 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.480442:INFO:main_context.cpp(136)] CEF initialized successfully.
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.480471:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 5 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.480488:INFO:main_context.cpp(138)] CEF version: 86.0.23+ga2c2edf+chromium-86.0.4240.193
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.481381:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 6 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.482409:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 7 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.784910:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 8 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: Created browser window for reuse: 0x2c00001
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.794570:WARNING:gpu_process_host.cc(1262)] The GPU process has crashed 9 time(s)
[09:14:02] [ForkJoinPool.commonPool-worker-13/ERROR] [Minecraft Launcher 0]: [1101/091402.794587:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
```

### Debug Code

FTB-DBGULUJOZUNON

### Describe the bug

No modpacks will launch, they all similar logs with the same sort of GPU process failures

### Steps to reproduce

1. try to launch any modpack
2. it fails before the minecraft launcher appears

### Expected behaviour

modpacks launch successfully

### Additional information

This started happening to me a few weeks ago, I updated to the latest FTB launcher, and none of my modpacks would launch any more. I'm not sure how long it had been since my last update, so I can't give a firm answer as which release the error started in.
I have updated my system to the latest video drivers and OS updates as of today.
I'm running a Ubuntu 20.04, a GTX970 and nvidia-470 drivers, and my steam games are working fine, so my OpenGL is working.
If I use the legacy launcher, I have no problems launching the modpacks I have installed there.
I noticed the logs also said that MineTogether couldn't start. I'm on a very high-latency satellite net connection (~700ms ping times) not sure if that's relevant, but it might be

**Comment by benevolentmadman** [comment]
with a bit of further research, I discovered this, which seems to be related: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468

**Comment by werybigmonk** [comment]
I installed ftb app today, and this was pretty much exact result for me as well. 
In my case launching minecraft launcher from ~/.ftba/bin/minecraft-launcher using command LC_ALL=C ./minecraft-launcher downloaded bunch of files and then FTB App was able to launch MC.

**Comment by MichaelHillcox** [comment]
Thank you for showing some potential fixes for the issues, we're looking into these issues internally and hopefully we can resolve the issues

**Comment by benevolentmadman** [comment]
> launching minecraft launcher from ~/.ftba/bin/minecraft-launcher using command LC_ALL=C ./minecraft-launcher

Thank you @werybigmonk that solved the issue for me. I assume that env var tells the launcher to refresh all it's cached files from the remote source?

**Comment by werybigmonk** [comment]
> > launching minecraft launcher from ~/.ftba/bin/minecraft-launcher using command LC_ALL=C ./minecraft-launcher
> 
> Thank you @werybigmonk that solved the issue for me. I assume that env var tells the launcher to refresh all it's cached files from the remote source?

LC_ALL is a locale variable, which some apps expect to be set, but at least in kubuntu 20 is not. C value is usually a safe fallback, if app/system doesn't support <lang>_<locale>.utf8 option. Not sure why it is needed here, but that looks to be Microsoft's fault. 
This could also be the cause for FTB App/unusable process issue, since it tries to utilise launcher to download minecraft files.

**Comment by MarkJeronimus** [comment]
Same here, and it's definitely a serious bug as it prevents newcomers from sticking. It gives them a sense of 'well, this isn't working' and they move on, possibly never giving FTB a second chance.
